### ISSUE TITLE
Max gyms

### ISSUE THREAD

**Issue by kvoorneveld** [driderr/Trimpz#1]
With me the script never buys gyms over 170, using the default settings. When I look at it, it seems the max should be 170 in some stages, but 10000 in the endgame. I have never seen it buy an additional gym over 170. Could you look into this?

**Comment by driderr** [comment]
Sorry about the delay.  I just noticed your issue entry.  I messed with all the default settings recently and completely restructured them.  Would you please see if you still have the issue?  It should buy up to 10k currently at any stage in the game.

**Comment by kvoorneveld** [comment]
It looks like it's working now. Thanks!

**Comment by driderr** [comment]
You're welcome!
