### ISSUE TITLE
Freeze after portal

### ISSUE THREAD

**Issue by Keraos** [driderr/Trimpz#3]
Every time that Trimpz portals the script assigns the user to traps, and then stops issuing further commands. If I manually push forward it will indicate that the script is running, not paused, but there are no active automated actions that I can see. Pausing/unpausing does not reactivate automation. Running the script again does re-enable the automation, but it does leave two instances of the script (the first frozen, the second functioning). If it helps, I'm doing  balance runs (portal at 41), most settings at default (eq tweaked for my perks).

Edit: It happened once this morning then on the most recent portal it didn't (first time in a couple days, I'll keep an eye on it)

**Comment by driderr** [comment]
Hello, and thanks for the feedback.  Would it be possible for you to paste a link to your save file and a screenshot of your Trimpz settings?  That would make it a lot easier to test since I've never run into that issue.

**Comment by Keraos** [comment]
Link to the picture: http://imgur.com/a/yTVfG

Save: [Trimpz.txt](https://github.com/driderr/Trimpz/files/159613/Trimpz.txt)

Let me know if there's anything else I can provide.

**Comment by driderr** [comment]
Let me know if that fixes it for you!

**Comment by Keraos** [comment]
It's been running perfectly all day. You are a champion, thanks!
