### ISSUE TITLE
Warpstations

### ISSUE THREAD

**Issue by kvoorneveld** [driderr/Trimpz#4]
I have the feeling your last update broke something regarding warpstations. For me it's not buying them anymore and when I buy one manually the script cancels the construction.

**Comment by driderr** [comment]
It would only do that if your breed time is always way too high.  What is your breed timer and hysteresis set at?  If those are normal, it's possible that the very first one is built too slowly and always raises your breed time very high and just gets cancelled.  Thanks for opening the issue, and I hope to hear back soon so I can fix this.

**Comment by driderr** [comment]
Please let me know how this latest update works for you.

**Comment by kvoorneveld** [comment]
It seems to be working fine now. Thanks!

Edit: It does not give a very polished feeling. It keeps queueing a lot of warstations and then building one and canceling the rest. If it would just build them one by one and would only build the next after checking if it can build another one it would run smoother Id guess.
