### ISSUE TITLE
Having a weird issue with your script..

### ISSUE THREAD

**Issue by JourneyOver** [driderr/Trimpz#6]
So decided to see how quickly your script could finish a crushed run versus spins script today but for some reason when ever I activate your script and reload trimps it doesn't seem to be able to load up the webpage for trimps completely, like it completely freezes the page right after it loads and nothing pops up in the console and even looking at the elements section in the dev console is completely blank. Not having this issue at all with spins script only seems to be happening with yours, so don't really know what the issue is. Happening on both chrome/firefox and on a new save and old save.

**Comment by driderr** [comment]
Well, that's pretty odd.  Never heard that one before.  How are you running the script?  And does the text at the top of the screen ever switch from "Trimps" to "Trimpz"?

**Comment by JourneyOver** [comment]
I'm running it through tampermonkey since I turned it into a userscript, but even doing it the bookmark way freezes the page as soon as press the bookmark. Either way I can't refresh the tab (nor open trimps up in another tab) either unless I completely end the tab through the task manager for chrome/firefox if trying to refresh the tab it'll just load infinitely, and if I try to close the tab it does nothing at all. 

Running it through tampermonkey it sometimes doesn't even show anything on screen other than just wood sometimes before it freezes without anything else showing up, and sometimes it'll show nothing before it freezes up, there are times when it'll load up all of the site but nothing changes and each way it just brings the transparent black screen layover (the layer that happens when you refresh the page for trimps) with it that just stays there. 

Running through bookmark it freezes without changing anything on the page at all other than showing the button in the battle section that tells me what its doing (its stuck on running) and the trimpz button that'll let me change options for the script. (which of course I can't click on since I can't click on any part of the site.)

**Comment by driderr** [comment]
I don't know anyone else using tampermonkey with my script, and I've never tried.  Since you're not even really getting into the script though, it's kind of hard to debug from here.  Can you in Chrome, make sure you're running trimps from github, load the bookmark to run Trimpz, hit F12, go to sources, then hit the pause icon (tooltip "pause script execution"), and tell me where in the Trimpz code it halts?  

edit: Actually, with the freeze, it would be helpful to have the pause button up and ready to go before you load Trimpz with the bookmark.

**Comment by JourneyOver** [comment]
Yes it's running from github - this is the userscript right here

```
// ==UserScript==
// @name         Auto Trimpz
// @namespace    https://github.com/driderr/Trimpz
// @version
// @description  Automate all the trimps!
// @author       driderr
// @include        *trimps.github.io*
// @include        *kongregate.com/games/GreenSatellite/trimps
// @grant        none
// ==/UserScript==
javascript:with(document)(head.appendChild(createElement('script')).src='https://rawgit.com/driderr/Trimpz/master/Trimpz.js')._;
```

and the bookmark I used to test was the same one from the bottom of the readme section, 

`javascript:document.body.appendChild(document.createElement('script')).setAttribute('src','https://rawgit.com/driderr/Trimpz/master/Trimpz.js');void(0);`

now here's the weird thing I went to load up your script again just now and it's not freezing anymore, idk what was causing it to freeze the past 2 days but it seems to be working now. tested it both through bookmark and my userscript. I'll continue running your script for now to see if it'll happen again at some point so I can figure out what might of been causing this issue but for now it's fixed..

**Comment by driderr** [comment]
Ok.  Glad it's working for you.  Feel free to reopen the issue if it becomes a problem again.
